version: '3.8'
services:
  abyssinia-bot:
    build: .
    ports:
      - "8037:8037"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      # Add your other environment variables here
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - TAVILY_API_KEY=${TAVILY_API_KEY}
      # etc...